apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: uber
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
  type: NodePort #ClusterIP